---
# handlers file for ansible-role-openvpn

- name: restart openvpn
  ansible.builtin.service:
    name: "{{ openvpn_service }}"
    state: restarted

- name: enable openvpn
  ansible.builtin.service:
    name: "{{ openvpn_service }}"
    enabled: true
    state: started

