---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include ansible-role-openvpn"
      include_role:
        name: "ansible-role-openvpn"
    #  roles:
    #    - ansible-role-openvpn #role: ../../ #openvpn #ansible-role-openvpn #/home/konstantin/Automation/Ansible/ansible-roles/OpenVPN/ansible-role-openvpn




#- name: Converge
#  hosts: all
#  gather_facts: false
#  tasks:
#    - name: Replace this task with one that validates your content
#      ansible.builtin.debug:
#        msg: "This is the effective test"
