---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: ubuntu:22.04  #almalinux
      #command: /sbin/init
    privileged: true
    pre_build_image: false

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
      roles_path: /home/konstantin/Automation/Ansible/ansible-roles/OpenVPN #../../
  playbooks:
    converge: converge.yml

verifier:
  name: ansible




#driver:
#  name: docker
#platforms:
#  - name: instance
#    image: quay.io/centos/centos:stream8
#    pre_build_image: true
